### ISSUE TITLE
Contact Me. CoopR needs help yes?

### ISSUE THREAD

**Issue by diveyez** [CoopR-Mod/CoopR-Mod#27]
You can find me at http://discord.devgru.club & @ https://devgru.club:1999 's git server.

**Comment by xetra11** [comment]
@diveyez Unfortunately your discord invitation link has expired. But for the sake of helping out please visit the link to our Discord Channel and just say hello! I am currently in Australia and it may take a moment for me to reply.

Links: https://discord.gg/mDfY93u
